server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/user/Documents/study/java-projects/msa-inflearn-git-local-repo
